version: '3'

env:
  GO111MODULE: "on"
  CGO_ENABLED: 0
  GOPROXY: "https://goproxy.cn,direct"

tasks:
  default:
    task -l
  build_api:
    desc: "build api server"
    cmds:
      - go build -o ./bin/api.exe ./cmd/api/main.go
  build_grpc:
    desc: "build grpc server"
    cmds:
      - go build -o ./bin/grpc.exe ./cmd/grpc/main.go
  gen_proto:
    desc: "gen proto file"
    env:
      protodir: "./internal/pb"
    cmds:
      - protoc --go_out=. --go_opt=paths=source_relative $protodir/*.proto
  gen_grpc:
    desc: "gen grpc file"
    env:
      protodir: "./internal/pb"
    cmds:
      - protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative $protodir/*.proto
  test:
    desc: "run unit test"
    cmds:
      - go test -cover -coverprofile=coverage.out ./internal/...
  mock_repo:
    desc: gen mock files
    cmds:
      - mockery --dir ./internal/domain/repo --name [a-z]+Repo --output ./internal/mock --outpkg mock --case underscore --with-expecter