// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.7
// source: internal/pb/hello.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type E int32

const (
	E_E_math E = 0
	E_E_eng  E = 1
)

// Enum value maps for E.
var (
	E_name = map[int32]string{
		0: "E_math",
		1: "E_eng",
	}
	E_value = map[string]int32{
		"E_math": 0,
		"E_eng":  1,
	}
)

func (x E) Enum() *E {
	p := new(E)
	*p = x
	return p
}

func (x E) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (E) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_pb_hello_proto_enumTypes[0].Descriptor()
}

func (E) Type() protoreflect.EnumType {
	return &file_internal_pb_hello_proto_enumTypes[0]
}

func (x E) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use E.Descriptor instead.
func (E) EnumDescriptor() ([]byte, []int) {
	return file_internal_pb_hello_proto_rawDescGZIP(), []int{0}
}

type Hello struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TestInt  int32            `protobuf:"varint,1,opt,name=test_int,json=testInt,proto3" json:"test_int,omitempty"`
	TestStr  string           `protobuf:"bytes,2,opt,name=test_str,json=testStr,proto3" json:"test_str,omitempty"`
	TestEnum E                `protobuf:"varint,3,opt,name=test_enum,json=testEnum,proto3,enum=pb.E" json:"test_enum,omitempty"`
	TestArr  []string         `protobuf:"bytes,4,rep,name=test_arr,json=testArr,proto3" json:"test_arr,omitempty"`
	TestItem []*Item          `protobuf:"bytes,5,rep,name=test_item,json=testItem,proto3" json:"test_item,omitempty"`
	TestMap  map[string]*Item `protobuf:"bytes,6,rep,name=test_map,json=testMap,proto3" json:"test_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Hello) Reset() {
	*x = Hello{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_hello_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_hello_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_internal_pb_hello_proto_rawDescGZIP(), []int{0}
}

func (x *Hello) GetTestInt() int32 {
	if x != nil {
		return x.TestInt
	}
	return 0
}

func (x *Hello) GetTestStr() string {
	if x != nil {
		return x.TestStr
	}
	return ""
}

func (x *Hello) GetTestEnum() E {
	if x != nil {
		return x.TestEnum
	}
	return E_E_math
}

func (x *Hello) GetTestArr() []string {
	if x != nil {
		return x.TestArr
	}
	return nil
}

func (x *Hello) GetTestItem() []*Item {
	if x != nil {
		return x.TestItem
	}
	return nil
}

func (x *Hello) GetTestMap() map[string]*Item {
	if x != nil {
		return x.TestMap
	}
	return nil
}

type Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemInt int32  `protobuf:"varint,1,opt,name=item_int,json=itemInt,proto3" json:"item_int,omitempty"`
	ItemStr string `protobuf:"bytes,2,opt,name=item_str,json=itemStr,proto3" json:"item_str,omitempty"`
}

func (x *Item) Reset() {
	*x = Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_hello_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_hello_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_internal_pb_hello_proto_rawDescGZIP(), []int{1}
}

func (x *Item) GetItemInt() int32 {
	if x != nil {
		return x.ItemInt
	}
	return 0
}

func (x *Item) GetItemStr() string {
	if x != nil {
		return x.ItemStr
	}
	return ""
}

type GreeterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GreeterRequest) Reset() {
	*x = GreeterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_hello_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GreeterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreeterRequest) ProtoMessage() {}

func (x *GreeterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_hello_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreeterRequest.ProtoReflect.Descriptor instead.
func (*GreeterRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_hello_proto_rawDescGZIP(), []int{2}
}

type GreeterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hello string `protobuf:"bytes,1,opt,name=hello,proto3" json:"hello,omitempty"`
}

func (x *GreeterResponse) Reset() {
	*x = GreeterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_hello_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GreeterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreeterResponse) ProtoMessage() {}

func (x *GreeterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_hello_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreeterResponse.ProtoReflect.Descriptor instead.
func (*GreeterResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_hello_proto_rawDescGZIP(), []int{3}
}

func (x *GreeterResponse) GetHello() string {
	if x != nil {
		return x.Hello
	}
	return ""
}

var File_internal_pb_hello_proto protoreflect.FileDescriptor

var file_internal_pb_hello_proto_rawDesc = []byte{
	0x0a, 0x17, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x68, 0x65,
	0x6c, 0x6c, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x9c, 0x02,
	0x0a, 0x05, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x65, 0x73, 0x74, 0x5f,
	0x69, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x74, 0x65, 0x73, 0x74, 0x49,
	0x6e, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x73, 0x74, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x65, 0x73, 0x74, 0x53, 0x74, 0x72, 0x12, 0x22, 0x0a,
	0x09, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x05, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x52, 0x08, 0x74, 0x65, 0x73, 0x74, 0x45, 0x6e, 0x75,
	0x6d, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x61, 0x72, 0x72, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x07, 0x74, 0x65, 0x73, 0x74, 0x41, 0x72, 0x72, 0x12, 0x25, 0x0a, 0x09,
	0x74, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x08, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x08, 0x74, 0x65, 0x73, 0x74, 0x49,
	0x74, 0x65, 0x6d, 0x12, 0x31, 0x0a, 0x08, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x6d, 0x61, 0x70, 0x18,
	0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f,
	0x2e, 0x54, 0x65, 0x73, 0x74, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x74,
	0x65, 0x73, 0x74, 0x4d, 0x61, 0x70, 0x1a, 0x44, 0x0a, 0x0c, 0x54, 0x65, 0x73, 0x74, 0x4d, 0x61,
	0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x1e, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x74, 0x65,
	0x6d, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x3c, 0x0a, 0x04,
	0x49, 0x74, 0x65, 0x6d, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x74, 0x12,
	0x19, 0x0a, 0x08, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x73, 0x74, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x69, 0x74, 0x65, 0x6d, 0x53, 0x74, 0x72, 0x22, 0x10, 0x0a, 0x0e, 0x47, 0x72,
	0x65, 0x65, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x27, 0x0a, 0x0f,
	0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x2a, 0x1a, 0x0a, 0x01, 0x45, 0x12, 0x0a, 0x0a, 0x06, 0x45, 0x5f,
	0x6d, 0x61, 0x74, 0x68, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x5f, 0x65, 0x6e, 0x67, 0x10,
	0x01, 0x32, 0x40, 0x0a, 0x07, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x12, 0x35, 0x0a, 0x08,
	0x53, 0x61, 0x79, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x72,
	0x65, 0x65, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x70,
	0x62, 0x2e, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_pb_hello_proto_rawDescOnce sync.Once
	file_internal_pb_hello_proto_rawDescData = file_internal_pb_hello_proto_rawDesc
)

func file_internal_pb_hello_proto_rawDescGZIP() []byte {
	file_internal_pb_hello_proto_rawDescOnce.Do(func() {
		file_internal_pb_hello_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_pb_hello_proto_rawDescData)
	})
	return file_internal_pb_hello_proto_rawDescData
}

var file_internal_pb_hello_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_pb_hello_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_pb_hello_proto_goTypes = []interface{}{
	(E)(0),                  // 0: pb.E
	(*Hello)(nil),           // 1: pb.Hello
	(*Item)(nil),            // 2: pb.Item
	(*GreeterRequest)(nil),  // 3: pb.GreeterRequest
	(*GreeterResponse)(nil), // 4: pb.GreeterResponse
	nil,                     // 5: pb.Hello.TestMapEntry
}
var file_internal_pb_hello_proto_depIdxs = []int32{
	0, // 0: pb.Hello.test_enum:type_name -> pb.E
	2, // 1: pb.Hello.test_item:type_name -> pb.Item
	5, // 2: pb.Hello.test_map:type_name -> pb.Hello.TestMapEntry
	2, // 3: pb.Hello.TestMapEntry.value:type_name -> pb.Item
	3, // 4: pb.Greeter.SayHello:input_type -> pb.GreeterRequest
	4, // 5: pb.Greeter.SayHello:output_type -> pb.GreeterResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_internal_pb_hello_proto_init() }
func file_internal_pb_hello_proto_init() {
	if File_internal_pb_hello_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_pb_hello_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Hello); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_hello_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_hello_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GreeterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_hello_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GreeterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_pb_hello_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_pb_hello_proto_goTypes,
		DependencyIndexes: file_internal_pb_hello_proto_depIdxs,
		EnumInfos:         file_internal_pb_hello_proto_enumTypes,
		MessageInfos:      file_internal_pb_hello_proto_msgTypes,
	}.Build()
	File_internal_pb_hello_proto = out.File
	file_internal_pb_hello_proto_rawDesc = nil
	file_internal_pb_hello_proto_goTypes = nil
	file_internal_pb_hello_proto_depIdxs = nil
}
